import './globals.css'
import type { Metadata } from 'next'
import {Nunito} from 'next/font/google';

export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

const front = Nunito({
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={front.className}>{children}</body>
    </html>
  )
}
