import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import Navbar from './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';
import RegisterModel from './components/models/RegisterModel';
import ToasterProvider from './providers/ToasterProvider';
import LoginModel from './components/models/LoginModel';
import RentModel from './components/models/RentModel';

import getCurrentUser from './actions/getCurrentUser';


export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
};

const front = Nunito({
  subsets: ["latin"]
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={front.className}>
        <ClientOnly>
          <ToasterProvider />
          <RentModel />
          <LoginModel />
          <RegisterModel />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        <div className='pb-20 pt-28'>
          {children}
        </div>
      </body>
    </html>
  );
}
